// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn9tb6_8aXH11s3wugAe-_uOkr6mNiqyY',
    appId: '1:445443035436:web:4e5fb675f702bc92329c89',
    messagingSenderId: '445443035436',
    projectId: 'fibasetest-ecdbd',
    authDomain: 'fibasetest-ecdbd.firebaseapp.com',
    storageBucket: 'fibasetest-ecdbd.appspot.com',
    measurementId: 'G-79VXVTZMCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb3vWAu4ttiSb9nS_4tE99GwGmcxlLSKw',
    appId: '1:445443035436:android:a6749db64d7a8c85329c89',
    messagingSenderId: '445443035436',
    projectId: 'fibasetest-ecdbd',
    storageBucket: 'fibasetest-ecdbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl8hlzuRif3JJ-d664ZTCXkWucfa2x8oo',
    appId: '1:445443035436:ios:e8ee024e072182c9329c89',
    messagingSenderId: '445443035436',
    projectId: 'fibasetest-ecdbd',
    storageBucket: 'fibasetest-ecdbd.appspot.com',
    iosBundleId: 'com.example.desktopTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl8hlzuRif3JJ-d664ZTCXkWucfa2x8oo',
    appId: '1:445443035436:ios:a593200d69adfb05329c89',
    messagingSenderId: '445443035436',
    projectId: 'fibasetest-ecdbd',
    storageBucket: 'fibasetest-ecdbd.appspot.com',
    iosBundleId: 'com.example.desktopTest.RunnerTests',
  );
}
